#!/bin/sh

function get_youtubedl {
    curl -L https://yt-dl.org/downloads/latest/youtube-dl -o ~/bin/youtube-dl
    chmod a+rx ~/bin/youtube-dl
}

main () {
    if [ -r "~/bin/youtube-dl" ]; then
        ~/bin/youtube-dl -U
    else
        get_youtubedl
    fi
}

# vim: fenc=utf-8 ft=sh
