#!/bin/sh

#
# start-mpd - Start or restart mpd service
#

# Terminate already running mpd service instance, if they exist.
# Wait until the processes have been shut down and start it again
#

if [[ -e "$ZDOTDIR/lib/functions.bash" ]]; then
    source $ZDOTDIR/lib/functions.bash
fi

# Functions

# Check if a ympd instance is running
is_running () {
    [[ -n "$(pgrep -u $UID -x mpd >/dev/null)" ]]
}

start_mpd () {
    mpd >/dev/null 2>&1 || die "Starting mpd service failed"
    pr-info "mpd service started"
}

stop_mpd () {
    mpd --kill >/dev/null 2>&1 &
    while is_running; do sleep 1; done
    pr-info "No mpd service is running anymore"
}

main () {
    pr-begin "Init mpd service"
    is_running && stop_mpd
    start_mpd
    pr-end $?  "mpd service finished with status $?"
}

main "$@"

# vim:fenc=utf-8:ft=sh:
